---
config:
  - credentials:
    	password: <PASSWORD>
    	username: <USERNAME>
  	deploy_branch: <BRANCHNAME>
  	id: <UUID>
  	project: "<REPO:AUTHOR/REPONAME>"
  	states:
      - "<STATUS:ONE>"
      - "<STATUS:TWO>"
